import { config, hasSupabase } from "./config";
import { embed } from "./embeddings";
import { getSupabaseAdmin } from "./supabase";
import { buildDocuments } from "./documents";

export type RetrievedChunk = {
  id: string;
  source: string;
  title: string;
  content: string;
  similarity: number;
};

function cosineSimilarity(a: number[], b: number[]): number {
  let dot = 0;
  let normA = 0;
  let normB = 0;
  for (let i = 0; i < a.length; i++) {
    dot += a[i] * b[i];
    normA += a[i] * a[i];
    normB += b[i] * b[i];
  }
  if (normA === 0 || normB === 0) return 0;
  return dot / (Math.sqrt(normA) * Math.sqrt(normB));
}

type LocalRecord = {
  id: string;
  source: string;
  title: string;
  content: string;
  embedding: number[];
};

let localCache: LocalRecord[] | null = null;

async function loadLocalEmbeddings(): Promise<LocalRecord[]> {
  if (localCache) return localCache;
  try {
    // Generated by `npm run ingest`. Optional fallback when Supabase is absent.
    const data = (await import("@/data/embeddings.local.json")).default;
    localCache = data as LocalRecord[];
  } catch {
    localCache = [];
  }
  return localCache;
}

/**
 * Retrieve the most relevant context chunks for a query.
 * Uses Supabase pgvector when configured, otherwise a local in-memory store.
 */
export async function retrieve(query: string): Promise<RetrievedChunk[]> {
  // No-vector mode: the profile is small, so just return everything as context.
  if (config.embeddingProvider === "none") {
    return buildDocuments().map((d) => ({
      id: d.id,
      source: d.source,
      title: d.title,
      content: d.content,
      similarity: 1,
    }));
  }

  const queryEmbedding = await embed(query);

  if (hasSupabase()) {
    const supabase = getSupabaseAdmin();
    const { data, error } = await supabase.rpc("match_documents", {
      query_embedding: queryEmbedding,
      match_count: config.topK,
    });
    if (error) throw new Error(`Supabase retrieval failed: ${error.message}`);
    return (data ?? []) as RetrievedChunk[];
  }

  const records = await loadLocalEmbeddings();
  return records
    .map((r) => ({
      id: r.id,
      source: r.source,
      title: r.title,
      content: r.content,
      similarity: cosineSimilarity(queryEmbedding, r.embedding),
    }))
    .sort((a, b) => b.similarity - a.similarity)
    .slice(0, config.topK);
}
